# Inserts a blank line between shell prompts
add_newline = true

[line_break]
disabled = true

[time]
disabled = false
format = 'ğŸ•™ $time($style) '

[[battery.display]]
threshold = 20

[kubernetes]
disabled = false
format = '[\[âˆ $context\]]($style) in '

[status]
disabled = false

