add_newline = true

[line_break]
disabled = true

[time]
disabled = false
format = ' ğŸ•™ $time($style) '
time_format = 'W%U, %a %T'

[[battery.display]]
threshold = 20

[kubernetes]
disabled = false
format = '[ âˆ $context ](inverted blue) in '

[aws]
disabled = false

[status]
disabled = false
