add_newline = true

[line_break]
disabled = true

[time]
disabled = false
format = 'ğŸ•™ $time($style) '

[[battery.display]]
threshold = 20

[kubernetes]
disabled = false
format = '[ âˆ $context ](inverted blue) in '

[status]
disabled = false

